### ISSUE TITLE
conversion error in css/main.scss

### ISSUE THREAD

**Issue by marcelm** [SciLifeLab/scilifelab.github.io#37]
When I run `jekyll serve --watch`, I get this error:

```
Configuration file: /.../scilifelab.github.io/_config.yml
            Source: /.../scilifelab.github.io
       Destination: /.../scilifelab.github.io/_site
      Generating... 
  Conversion error: There was an error converting 'css/main.scss'.
jekyll 2.0.3 | Error:  Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $p..."
```

I have no idea how to fix that - the string "webkit-image" doesn’t even occur in the `css/main.scss` file. Any ideas?

**Comment by dahlo** [comment]
Have not tried to change anything, but i did a grep -r webkit-image ./* in the repo and it looks like only some files in ./_sass/bourbon/helpers/ have the lines the error message mentions. Probably involved through the imports in main.scss (@import 'bourbon/bourbon';)

Cheers
Martin

**Comment by ewels** [comment]
One for @robinandeer..

I'm currently working on v2 of the site which will have a more user-friendly web based administration side (based on WordPress) to avoid the pains of running the site locally..

Phil

**Comment by robinandeer** [comment]
You seems to run an older version of Jekyll which could cause problems. I would first make sure to upgrade the ``jekyll`` (2.4.0) and ``sass`` (3.4.9) gems because everything then should work. ``sass`` has added some new features I believe in the recent versions.

But as mentioned above we are also working on a new version of the site which Phil should have whipped up in no time, right? :wink:

**Comment by ewels** [comment]
I'm getting there.. No promises about when it will actually go live though ;)

**Comment by marcelm** [comment]
The Jekyll version is the one that came with Ubuntu 14.10. I also tried to use the `gem install` way, but got other errors. Here is what I did:

```
gem install --user-install jekyll bundle
```
Then I added `$HOME/.gem/ruby/2.1.0/bin` to my PATH. Finally, running `jekyll serve` results in this:

```
/home/marcel/.gem/ruby/2.1.0/gems/jekyll-2.5.3/lib/jekyll.rb:166:in `<top (required)>': undefined method `gracefully_require' for Jekyll::Deprecator:Class (NoMethodError)
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /home/marcel/.gem/ruby/2.1.0/gems/jekyll-2.5.3/bin/jekyll:6:in `<top (required)>'
        from /home/marcel/.gem/ruby/2.1.0/bin/jekyll:23:in `load'
        from /home/marcel/.gem/ruby/2.1.0/bin/jekyll:23:in `<main>'
```
I tried this also four weeks ago and got stuck at the same point - but with a totally different error message. If nothing else, this illustrates that it would be *very* helpful to have a version of the site that is easier to use! (hint, hint)

**Comment by ewels** [comment]
You can add to the development version of the new site if you like :) It's running locally on my laptop and the front end doesn't work properly yet, but as of about three minutes ago you can make the new posts! And as of this morning the github authentication should work (you need to be a member of SciLifeLab github organisation).

When it's closer to being finished I'll clone the database across to the production server.

http://130.229.42.149:8888/wp-admin/
